const services = [
 {name:'Gov.br',tag:'Identidade digital',description:'Acesse sua conta gov.br para encontrar serviços federais e acompanhar solicitações.',examples:'Conta gov.br · serviços federais',url:'https://www.gov.br/pt-br'},
 {name:'Meu INSS',tag:'Previdência',description:'Consulte benefícios, extratos e orientações sobre aposentadoria e outros pedidos ao INSS.',examples:'Aposentadoria · benefícios · extratos',url:'https://meu.inss.gov.br/'},
 {name:'Receita Federal',tag:'Documentos e impostos',description:'Encontre orientações para CPF, imposto de renda e outros serviços tributários federais.',examples:'CPF · imposto de renda',url:'https://www.gov.br/receitafederal/pt-br'},
 {name:'Meu SUS Digital',tag:'Saúde',description:'Veja informações de saúde disponíveis para você, como histórico de vacinação e atendimentos.',examples:'Vacinas · saúde · SUS',url:'https://meususdigital.saude.gov.br/'},
 {name:'CAIXA',tag:'Benefícios e serviços',description:'Consulte informações oficiais sobre benefícios sociais e serviços da Caixa Econômica Federal.',examples:'Benefícios · Caixa',url:'https://www.caixa.gov.br/'},
 {name:'Detran-MG',tag:'Trânsito em Minas',description:'Encontre informações sobre habilitação, veículos, multas e serviços de trânsito de Minas Gerais.',examples:'CNH · veículos · multas',url:'https://www.transito.mg.gov.br/'},
 {name:'Prefeitura de Nanuque',tag:'Serviços municipais',description:'Acesse o portal do município para informações e serviços locais.',examples:'Nanuque · prefeitura',url:'https://www.nanuque.mg.gov.br/portal/servicos_online'}
];
const cards=document.querySelector('#cards'), input=document.querySelector('#busca'), count=document.querySelector('#contagem'), empty=document.querySelector('#vazio');
const normalize=value=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function render(){const q=normalize(input.value.trim());const filtered=services.filter(s=>normalize([s.name,s.tag,s.description,s.examples].join(' ')).includes(q));cards.replaceChildren();for(const [i,s] of filtered.entries()){const article=document.createElement('article');article.className='card';const meta=document.createElement('div');meta.className='card-meta';const number=document.createElement('span');number.className='number';number.textContent=String(services.indexOf(s)+1).padStart(2,'0');const tag=document.createElement('span');tag.className='tag';tag.textContent=s.tag;meta.append(number,tag);const h=document.createElement('h3');h.textContent=s.name;const p=document.createElement('p');p.textContent=s.description;const examples=document.createElement('small');examples.textContent=s.examples;const a=document.createElement('a');a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Acessar site oficial ↗';a.setAttribute('aria-label',`Acessar site oficial de ${s.name} (abre em nova aba)`);article.append(meta,h,p,examples,a);cards.append(article)}count.textContent=`${filtered.length} ${filtered.length===1?'serviço encontrado':'serviços encontrados'}`;empty.hidden=filtered.length!==0}input.addEventListener('input',render);render();
